# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-numpy 
    - python-lxml
    - python-tornado

language: python
python: 
   #- 2.7 
   - 3.7


env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_validatev1

install:     
    - pip install scipy # Why is this needed? Doesn't seem to get installed correctly with addons above...
    - pip install tables # Ditto
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install future pandas matplotlib-scalebar bokeh # For NetPyNE

script:
    - omv all -V
    - omv list-engines -V
    
    
    

